repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--explicit-package-bases]
        additional_dependencies: [
          pydantic,
          pyspark,
          types-requests,
          pytest
        ]

  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: uv run pytest --cov=src --cov-report=term-missing
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
